allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(":app")
}

subprojects {
    project.tasks.configureEach { task ->
        if (task.class.name.contains("KotlinCompile")) {
            try {
                task.kotlinOptions.freeCompilerArgs += ["-Xskip-metadata-version-check"]
            } catch (Exception e) {}
        }
    }
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
