// File generated by FlutterFire CLI & configured for Adhkar 365
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        // Fallback for non-Android platforms until configured
        return android;
    }
  }

  static const String _androidApiKey = String.fromEnvironment(
    'FIREBASE_ANDROID_API_KEY',
    defaultValue: 'AIzaSyBWLKSbVtQ-u5hEr9LXMTL7x0d4MBe5PGg',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: _androidApiKey,
    appId: '1:622768800935:android:609e1d06e5d0205f180782',
    messagingSenderId: '622768800935',
    projectId: 'adhkar365',
    storageBucket: 'adhkar365.firebasestorage.app',
  );
}
