import json
import os

translations = {
    "en": {
        "onb_goal_title": "What is your main goal?",
        "onb_goal_protection": "Morning & Evening Protection",
        "onb_goal_habit": "Build a daily Dhikr habit",
        "onb_goal_peace": "Find peace during difficult times",
        "onb_goal_sunnah": "Complete Sunnah supplications",
        "onb_time_title": "When is your best time for Dhikr?",
        "onb_time_fajr": "After Fajr",
        "onb_time_asr": "After Asr",
        "onb_time_sleep": "Before Sleep",
        "onb_time_anytime": "Anytime",
        "onb_welcome": "Welcome",
        "onb_begin": "Begin My Journey",
        "onb_step_lang": "Choose Your Language",
        "onb_loc_title": "Set Up Prayer Times",
        "onb_loc_subtitle": "Enable location for accurate prayer times and automatic Adhkar reminders",
        "onb_loc_detecting": "Locating your city…",
        "onb_loc_success": "Location detected",
        "onb_loc_manual": "Set Location Manually",
        "onb_loc_enable": "Enable Location (GPS)",
        "onb_summary_title": "Your Daily Plan",
        "onb_summary_goal": "Your Goal",
        "onb_summary_time": "Preferred Time",
        "onb_summary_location": "Location"
    },
    "bn": {
        "onb_goal_title": "আপনার মূল লক্ষ্য কী?",
        "onb_goal_protection": "সকাল ও সন্ধ্যার নিরাপত্তা",
        "onb_goal_habit": "প্রতিদিনের যিকিরের অভ্যাস গড়ে তোলা",
        "onb_goal_peace": "কঠিন সময়ে অন্তরে শান্তি লাভ",
        "onb_goal_sunnah": "সুন্নাহ নির্দেশিত দু'আ পূর্ণ করা",
        "onb_time_title": "যিকিরের জন্য আপনার সবচেয়ে পছন্দের সময় কোনটি?",
        "onb_time_fajr": "ফজরের পর",
        "onb_time_asr": "আসরের পর",
        "onb_time_sleep": "ঘুমানোর আগে",
        "onb_time_anytime": "যেকোনো সময়",
        "onb_welcome": "স্বাগতম",
        "onb_begin": "আমার যাত্রা শুরু করুন",
        "onb_step_lang": "আপনার ভাষা নির্বাচন করুন",
        "onb_loc_title": "নামাজের সময় নির্ধারণ করুন",
        "onb_loc_subtitle": "সঠিক নামাজের সময় এবং স্বয়ংক্রিয় আযকার রিমাইন্ডারের জন্য লোকেশন চালু করুন",
        "onb_loc_detecting": "আপনার শহর খোঁজা হচ্ছে…",
        "onb_loc_success": "লোকেশন সফলভাবে সনাক্ত হয়েছে",
        "onb_loc_manual": "ম্যানুয়ালি লোকেশন সেট করুন",
        "onb_loc_enable": "লোকেশন (GPS) চালু করুন",
        "onb_summary_title": "আপনার দৈনিক পরিকল্পনা",
        "onb_summary_goal": "আপনার লক্ষ্য",
        "onb_summary_time": "পছন্দের সময়",
        "onb_summary_location": "লোকেশন"
    },
    "ar": {
        "onb_goal_title": "ما هو هدفك الأساسي؟",
        "onb_goal_protection": "حماية الصباح والمساء",
        "onb_goal_habit": "بناء عادة الذكر اليومية",
        "onb_goal_peace": "العثور على السكينة في الأوقات الصعبة",
        "onb_goal_sunnah": "إتمام أدعية السنة النبوية",
        "onb_time_title": "متى هو أفضل وقت للذكر بالنسبة لك؟",
        "onb_time_fajr": "بعد الفجر",
        "onb_time_asr": "بعد العصر",
        "onb_time_sleep": "قبل النوم",
        "onb_time_anytime": "في أي وقت",
        "onb_welcome": "أهلاً بك",
        "onb_begin": "ابدأ رحلتي",
        "onb_step_lang": "اختر لغتك",
        "onb_loc_title": "إعداد أوقات الصلاة",
        "onb_loc_subtitle": "قم بتفعيل الموقع للحصول على أوقات صلاة دقيقة وتنبيهات أذكار تلقائية",
        "onb_loc_detecting": "جاري تحديد مدينتك…",
        "onb_loc_success": "تم تحديد الموقع",
        "onb_loc_manual": "تحديد الموقع يدوياً",
        "onb_loc_enable": "تفعيل الموقع (GPS)",
        "onb_summary_title": "خطتك اليومية",
        "onb_summary_goal": "هدفك",
        "onb_summary_time": "الوقت المفضل",
        "onb_summary_location": "الموقع"
    },
    "ur": {
        "onb_goal_title": "آپ کا بنیادی مقصد کیا ہے؟",
        "onb_goal_protection": "صبح و شام کی حفاظت",
        "onb_goal_habit": "روزانہ اذکار کی عادت بنانا",
        "onb_goal_peace": "مشکل وقت میں دلی سکون پانا",
        "onb_goal_sunnah": "سنت دعائیں مکمل کرنا",
        "onb_time_title": "اذکار کے لیے آپ کا بہترین وقت کون سا ہے؟",
        "onb_time_fajr": "فجر کے بعد",
        "onb_time_asr": "عصر کے بعد",
        "onb_time_sleep": "سونے سے پہلے",
        "onb_time_anytime": "کسی بھی وقت",
        "onb_welcome": "خوش آمدید",
        "onb_begin": "میرا سفر شروع کریں",
        "onb_step_lang": "اپنی زبان منتخب کریں",
        "onb_loc_title": "نماز کے اوقات کا تعین کریں",
        "onb_loc_subtitle": "درست نماز کے اوقات اور خودکار اذکار یاد دہانی کے لیے لوکیشن فعال کریں",
        "onb_loc_detecting": "آپ کے شہر کی تلاش جاری ہے…",
        "onb_loc_success": "مقام مل گیا",
        "onb_loc_manual": "دستی طور پر مقام درج کریں",
        "onb_loc_enable": "مقام (GPS) فعال کریں",
        "onb_summary_title": "آپ کا روزانہ کا منصوبہ",
        "onb_summary_goal": "آپ کا مقصد",
        "onb_summary_time": "پسندیدہ وقت",
        "onb_summary_location": "مقام"
    },
    "id": {
        "onb_goal_title": "Apa tujuan utama Anda?",
        "onb_goal_protection": "Perlindungan Pagi & Petang",
        "onb_goal_habit": "Membangun kebiasaan Dzikir harian",
        "onb_goal_peace": "Menemukan ketenangan saat masa sulit",
        "onb_goal_sunnah": "Menyempurnakan doa Sunnah",
        "onb_time_title": "Kapan waktu terbaik Anda untuk berdzikir?",
        "onb_time_fajr": "Setelah Subuh",
        "onb_time_asr": "Setelah Ashar",
        "onb_time_sleep": "Sebelum Tidur",
        "onb_time_anytime": "Kapan saja",
        "onb_welcome": "Selamat Datang",
        "onb_begin": "Mulai Perjalanan Saya",
        "onb_step_lang": "Pilih Bahasa Anda",
        "onb_loc_title": "Atur Waktu Shalat",
        "onb_loc_subtitle": "Aktifkan lokasi untuk waktu shalat yang akurat dan pengingat Adhkar otomatis",
        "onb_loc_detecting": "Mendeteksi kota Anda…",
        "onb_loc_success": "Lokasi terdeteksi",
        "onb_loc_manual": "Atur Lokasi Secara Manual",
        "onb_loc_enable": "Aktifkan Lokasi (GPS)",
        "onb_summary_title": "Rencana Harian Anda",
        "onb_summary_goal": "Tujuan Anda",
        "onb_summary_time": "Waktu Pilihan",
        "onb_summary_location": "Lokasi"
    },
    "tr": {
        "onb_goal_title": "Temel hedefiniz nedir?",
        "onb_goal_protection": "Sabah ve Akşam Koruması",
        "onb_goal_habit": "Günlük zikir alışkanlığı kazanmak",
        "onb_goal_peace": "Zor zamanlarda huzur bulmak",
        "onb_goal_sunnah": "Sünnet dualarını tamamlamak",
        "onb_time_title": "Zikir için en uygun vaktiniz ne zaman?",
        "onb_time_fajr": "Sabah Namazından Sonra",
        "onb_time_asr": "İkindiden Sonra",
        "onb_time_sleep": "Uyumadan Önce",
        "onb_time_anytime": "Her zaman",
        "onb_welcome": "Hoş Geldiniz",
        "onb_begin": "Yolculuğuma Başla",
        "onb_step_lang": "Dilinizi Seçin",
        "onb_loc_title": "Namaz Vakitlerini Ayarla",
        "onb_loc_subtitle": "Doğru namaz vakitleri ve otomatik zikir hatırlatıcıları için konumu etkinleştirin",
        "onb_loc_detecting": "Şehriniz bulunuyor…",
        "onb_loc_success": "Konum belirlendi",
        "onb_loc_manual": "Konumu Elle Ayarla",
        "onb_loc_enable": "Konumu Etkinleştir (GPS)",
        "onb_summary_title": "Günlük Planınız",
        "onb_summary_goal": "Hedefiniz",
        "onb_summary_time": "Tercih Edilen Vakit",
        "onb_summary_location": "Konum"
    },
    "ms": {
        "onb_goal_title": "Apakah matlamat utama anda?",
        "onb_goal_protection": "Perlindungan Pagi & Petang",
        "onb_goal_habit": "Membina amalan zikir harian",
        "onb_goal_peace": "Mencari ketenangan pada saat sukar",
        "onb_goal_sunnah": "Menyempurnakan doa-doa Sunnah",
        "onb_time_title": "Bilakah waktu terbaik anda untuk berzikir?",
        "onb_time_fajr": "Selepas Subuh",
        "onb_time_asr": "Selepas Asar",
        "onb_time_sleep": "Sebelum Tidur",
        "onb_time_anytime": "Bila-bila masa",
        "onb_welcome": "Selamat Datang",
        "onb_begin": "Mulakan Perjalanan Saya",
        "onb_step_lang": "Pilih Bahasa Anda",
        "onb_loc_title": "Tetapkan Waktu Solat",
        "onb_loc_subtitle": "Dayakan lokasi untuk waktu solat yang tepat dan peringatan Adhkar automatik",
        "onb_loc_detecting": "Mengesan bandar anda…",
        "onb_loc_success": "Lokasi dikesan",
        "onb_loc_manual": "Tetapkan Lokasi Secara Manual",
        "onb_loc_enable": "Dayakan Lokasi (GPS)",
        "onb_summary_title": "Pelan Harian Anda",
        "onb_summary_goal": "Matlamat Anda",
        "onb_summary_time": "Waktu Pilihan",
        "onb_summary_location": "Lokasi"
    },
    "fr": {
        "onb_goal_title": "Quel est votre objectif principal ?",
        "onb_goal_protection": "Protection du Matin et du Soir",
        "onb_goal_habit": "Développer une habitude quotidienne de Dhikr",
        "onb_goal_peace": "Trouver la paix dans les moments difficiles",
        "onb_goal_sunnah": "Compléter les invocations de la Sunnah",
        "onb_time_title": "Quel est votre meilleur moment pour le Dhikr ?",
        "onb_time_fajr": "Après Fajr",
        "onb_time_asr": "Après Asr",
        "onb_time_sleep": "Avant de dormir",
        "onb_time_anytime": "À tout moment",
        "onb_welcome": "Bienvenue",
        "onb_begin": "Commencer mon voyage",
        "onb_step_lang": "Choisissez votre langue",
        "onb_loc_title": "Configurer les horaires de prière",
        "onb_loc_subtitle": "Activez la localisation pour des horaires de prière précis et des rappels automatiques",
        "onb_loc_detecting": "Localisation de votre ville…",
        "onb_loc_success": "Localisation détectée",
        "onb_loc_manual": "Définir la position manuellement",
        "onb_loc_enable": "Activer la localisation (GPS)",
        "onb_summary_title": "Votre plan quotidien",
        "onb_summary_goal": "Votre objectif",
        "onb_summary_time": "Moment préféré",
        "onb_summary_location": "Emplacement"
    },
    "es": {
        "onb_goal_title": "¿Cuál es tu objetivo principal?",
        "onb_goal_protection": "Protección de Mañana y Tarde",
        "onb_goal_habit": "Construir un hábito diario de Dhikr",
        "onb_goal_peace": "Encontrar paz en momentos difíciles",
        "onb_goal_sunnah": "Completar súplicas de la Sunnah",
        "onb_time_title": "¿Cuándo es tu mejor momento para el Dhikr?",
        "onb_time_fajr": "Después de Fajr",
        "onb_time_asr": "Después de Asr",
        "onb_time_sleep": "Antes de dormir",
        "onb_time_anytime": "En cualquier momento",
        "onb_welcome": "Bienvenido",
        "onb_begin": "Comenzar mi viaje",
        "onb_step_lang": "Elige tu idioma",
        "onb_loc_title": "Configurar horarios de oración",
        "onb_loc_subtitle": "Activa la ubicación para horarios de oración precisos y recordatorios automáticos",
        "onb_loc_detecting": "Localizando tu ciudad…",
        "onb_loc_success": "Ubicación detectada",
        "onb_loc_manual": "Establecer ubicación manualmente",
        "onb_loc_enable": "Activar ubicación (GPS)",
        "onb_summary_title": "Tu plan diario",
        "onb_summary_goal": "Tu objetivo",
        "onb_summary_time": "Hora preferida",
        "onb_summary_location": "Ubicación"
    },
    "de": {
        "onb_goal_title": "Was ist dein Hauptziel?",
        "onb_goal_protection": "Morgen- & Abendschutz",
        "onb_goal_habit": "Eine tägliche Dhikr-Gewohnheit aufbauen",
        "onb_goal_peace": "Ruhe in schwierigen Zeiten finden",
        "onb_goal_sunnah": "Sunnah-Bittgebete vervollständigen",
        "onb_time_title": "Wann ist deine beste Zeit für Dhikr?",
        "onb_time_fajr": "Nach dem Fajr",
        "onb_time_asr": "Nach dem Asr",
        "onb_time_sleep": "Vor dem Schlafen",
        "onb_time_anytime": "Jederzeit",
        "onb_welcome": "Willkommen",
        "onb_begin": "Meine Reise beginnen",
        "onb_step_lang": "Wähle deine Sprache",
        "onb_loc_title": "Gebetszeiten einrichten",
        "onb_loc_subtitle": "Aktiviere den Standort für genaue Gebetszeiten und automatische Adhkar-Erinnerungen",
        "onb_loc_detecting": "Deine Stadt wird gesucht…",
        "onb_loc_success": "Standort erkannt",
        "onb_loc_manual": "Standort manuell festlegen",
        "onb_loc_enable": "Standort aktivieren (GPS)",
        "onb_summary_title": "Dein Tagesplan",
        "onb_summary_goal": "Dein Ziel",
        "onb_summary_time": "Bevorzugte Zeit",
        "onb_summary_location": "Standort"
    },
    "hi": {
        "onb_goal_title": "आपका मुख्य लक्ष्य क्या है?",
        "onb_goal_protection": "सुबह और शाम की सुरक्षा",
        "onb_goal_habit": "दैनिक अज़कार की आदत बनाना",
        "onb_goal_peace": "कठिन समय में दिल का सुकून पाना",
        "onb_goal_sunnah": "सुन्नत दुआओं को पूरा करना",
        "onb_time_title": "अज़कार के लिए आपका सबसे अच्छा समय कौन सा है?",
        "onb_time_fajr": "फ़ज्र के बाद",
        "onb_time_asr": "असर के बाद",
        "onb_time_sleep": "सोने से पहले",
        "onb_time_anytime": "किसी भी समय",
        "onb_welcome": "स्वागत है",
        "onb_begin": "मेरी यात्रा शुरू करें",
        "onb_step_lang": "अपनी भाषा चुनें",
        "onb_loc_title": "नमाज़ के समय सेट करें",
        "onb_loc_subtitle": "सटीक नमाज़ के समय और स्वचालित अज़कार रिमाइंडर के लिए स्थान सक्षम करें",
        "onb_loc_detecting": "आपका शहर खोजा जा रहा है…",
        "onb_loc_success": "स्थान पहचाना गया",
        "onb_loc_manual": "स्थान मैन्युअल रूप से सेट करें",
        "onb_loc_enable": "स्थान (GPS) सक्षम करें",
        "onb_summary_title": "आपकी दैनिक योजना",
        "onb_summary_goal": "आपका लक्ष्य",
        "onb_summary_time": "पसंदीदा समय",
        "onb_summary_location": "स्थान"
    },
    "ru": {
        "onb_goal_title": "Какова ваша главная цель?",
        "onb_goal_protection": "Утренняя и вечерняя защита",
        "onb_goal_habit": "Выработать ежедневную привычку зикра",
        "onb_goal_peace": "Обрести душевный покой в трудные времена",
        "onb_goal_sunnah": "Совершать сунну мольбы",
        "onb_time_title": "Когда для вас лучшее время для зикра?",
        "onb_time_fajr": "После Фаджра",
        "onb_time_asr": "После Асра",
        "onb_time_sleep": "Перед сном",
        "onb_time_anytime": "В любое время",
        "onb_welcome": "Добро пожаловать",
        "onb_begin": "Начать путешествие",
        "onb_step_lang": "Выберите язык",
        "onb_loc_title": "Настроить время намаза",
        "onb_loc_subtitle": "Включите геолокацию для точного расписания молитв и напоминаний об азкаре",
        "onb_loc_detecting": "Определение вашего города…",
        "onb_loc_success": "Местоположение определено",
        "onb_loc_manual": "Указать город вручную",
        "onb_loc_enable": "Включить геопозицию (GPS)",
        "onb_summary_title": "Ваш ежедневный план",
        "onb_summary_goal": "Ваша цель",
        "onb_summary_time": "Удобное время",
        "onb_summary_location": "Местоположение"
    },
    "pt": {
        "onb_goal_title": "Qual é o seu principal objetivo?",
        "onb_goal_protection": "Proteção Matinal e Noturna",
        "onb_goal_habit": "Construir o hábito diário de Dhikr",
        "onb_goal_peace": "Encontrar paz em momentos difíceis",
        "onb_goal_sunnah": "Completar as súplicas da Sunnah",
        "onb_time_title": "Qual é a sua melhor hora para o Dhikr?",
        "onb_time_fajr": "Depois do Fajr",
        "onb_time_asr": "Depois do Asr",
        "onb_time_sleep": "Antes de Dormir",
        "onb_time_anytime": "A qualquer momento",
        "onb_welcome": "Bem-vindo",
        "onb_begin": "Iniciar Minha Jornada",
        "onb_step_lang": "Escolha o seu idioma",
        "onb_loc_title": "Configurar Horários de Oração",
        "onb_loc_subtitle": "Ative a localização para horários de oração precisos e lembretes de Adhkar",
        "onb_loc_detecting": "Localizando sua cidade…",
        "onb_loc_success": "Localização detectada",
        "onb_loc_manual": "Definir Localização Manualmente",
        "onb_loc_enable": "Ativar Localização (GPS)",
        "onb_summary_title": "Seu Plano Diário",
        "onb_summary_goal": "Seu Objetivo",
        "onb_summary_time": "Horário Preferido",
        "onb_summary_location": "Localização"
    },
    "it": {
        "onb_goal_title": "Qual è il tuo obiettivo principale?",
        "onb_goal_protection": "Protezione Mattutina e Seral",
        "onb_goal_habit": "Costruire un'abitudine quotidiana di Dhikr",
        "onb_goal_peace": "Trovare pace nei momenti difficili",
        "onb_goal_sunnah": "Completare le suppliche della Sunnah",
        "onb_time_title": "Qual è il tuo momento migliore per il Dhikr?",
        "onb_time_fajr": "Dopo Fajr",
        "onb_time_asr": "Dopo Asr",
        "onb_time_sleep": "Prima di dormire",
        "onb_time_anytime": "In qualsiasi momento",
        "onb_welcome": "Benvenuto",
        "onb_begin": "Inizia il mio viaggio",
        "onb_step_lang": "Scegli la tua lingua",
        "onb_loc_title": "Imposta gli orari di preghiera",
        "onb_loc_subtitle": "Attiva la geolocalizzazione per orari di preghiera precisi e promemoria Adhkar",
        "onb_loc_detecting": "Rilevamento della tua città…",
        "onb_loc_success": "Posizione rilevata",
        "onb_loc_manual": "Imposta posizione manualmente",
        "onb_loc_enable": "Attiva posizione (GPS)",
        "onb_summary_title": "Il tuo piano quotidiano",
        "onb_summary_goal": "Il tuo obiettivo",
        "onb_summary_time": "Orario preferito",
        "onb_summary_location": "Posizione"
    },
    "nl": {
        "onb_goal_title": "Wat is je hoofddoel?",
        "onb_goal_protection": "Ochtend- en Avondbescherming",
        "onb_goal_habit": "Bouw een dagelijkse Dhikr-gewoonte op",
        "onb_goal_peace": "Vrede vinden in moeilijke tijden",
        "onb_goal_sunnah": "Voltooi Sunnah-smeekbeden",
        "onb_time_title": "Wanneer is je beste tijd voor Dhikr?",
        "onb_time_fajr": "Na Fajr",
        "onb_time_asr": "Na Asr",
        "onb_time_sleep": "Voor het slapengaan",
        "onb_time_anytime": "Altijd",
        "onb_welcome": "Welkom",
        "onb_begin": "Begin Mijn Reis",
        "onb_step_lang": "Kies je taal",
        "onb_loc_title": "Gebedstijden instellen",
        "onb_loc_subtitle": "Schakel locatie in voor nauwkeurige gebedstijden en automatische herinneringen",
        "onb_loc_detecting": "Je stad bepalen…",
        "onb_loc_success": "Locatie gevonden",
        "onb_loc_manual": "Locatie handmatig instellen",
        "onb_loc_enable": "Locatie inschakelen (GPS)",
        "onb_summary_title": "Je Dagelijkse Plan",
        "onb_summary_goal": "Jouw Doel",
        "onb_summary_time": "Voorkeurstijd",
        "onb_summary_location": "Locatie"
    },
    "ja": {
        "onb_goal_title": "主な目標は何ですか？",
        "onb_goal_protection": "朝夕の保護の祈り",
        "onb_goal_habit": "毎日のズィクルの習慣を作る",
        "onb_goal_peace": "困難な時に心の平安を見つける",
        "onb_goal_sunnah": "スンナの祈りを完成させる",
        "onb_time_title": "ズィクルに最適な時間はいつですか？",
        "onb_time_fajr": "ファジュル後",
        "onb_time_asr": "アスル後",
        "onb_time_sleep": "就寝前",
        "onb_time_anytime": "いつでも",
        "onb_welcome": "ようこそ",
        "onb_begin": "私の旅を始める",
        "onb_step_lang": "言語を選択",
        "onb_loc_title": "礼拝時間の設定",
        "onb_loc_subtitle": "正確な礼拝時間と自動リマインダーのために位置情報を有効にしてください",
        "onb_loc_detecting": "都市を特定中…",
        "onb_loc_success": "位置を検出しました",
        "onb_loc_manual": "手動で都市を設定",
        "onb_loc_enable": "位置情報を有効化 (GPS)",
        "onb_summary_title": "あなたの毎日のプラン",
        "onb_summary_goal": "あなたの目標",
        "onb_summary_time": "好みの時間帯",
        "onb_summary_location": "所在地"
    },
    "zh": {
        "onb_goal_title": "您的主要目标是什么？",
        "onb_goal_protection": "晨昏庇护赞念",
        "onb_goal_habit": "养成每日赞念习惯",
        "onb_goal_peace": "在困难时刻寻得内心宁静",
        "onb_goal_sunnah": "完成圣行祈祷词",
        "onb_time_title": "您最适合赞念的时间是？",
        "onb_time_fajr": "晨礼之后",
        "onb_time_asr": "晡礼之后",
        "onb_time_sleep": "睡前",
        "onb_time_anytime": "随时",
        "onb_welcome": "欢迎",
        "onb_begin": "开始我的旅程",
        "onb_step_lang": "选择您的语言",
        "onb_loc_title": "设置祈祷时间",
        "onb_loc_subtitle": "启用定位以获取精准祈祷时间和自动赞念提醒",
        "onb_loc_detecting": "正在定位您的城市…",
        "onb_loc_success": "已成功定位",
        "onb_loc_manual": "手动设置位置",
        "onb_loc_enable": "启用定位 (GPS)",
        "onb_summary_title": "您的每日计划",
        "onb_summary_goal": "您的目标",
        "onb_summary_time": "偏好时间",
        "onb_summary_location": "位置"
    },
    "ta": {
        "onb_goal_title": "உங்கள் முக்கிய குறிக்கோள் என்ன?",
        "onb_goal_protection": "காலை & மாலை பாதுகாப்பு",
        "onb_goal_habit": "தினசரி திக்ர் பழக்கத்தை உருவாக்குதல்",
        "onb_goal_peace": "சிரமமான நேரங்களில் அமைதி காணல்",
        "onb_goal_sunnah": "சுன்னத் துஆக்களை நிறைவு செய்தல்",
        "onb_time_title": "திக்ர் செய்ய உங்கள் சிறந்த நேரம் எது?",
        "onb_time_fajr": "ஃபஜ்ருக்குப் பிறகு",
        "onb_time_asr": "அஸருக்குப் பிறகு",
        "onb_time_sleep": "தூங்கும் முன்",
        "onb_time_anytime": "எந்த நேரத்திலும்",
        "onb_welcome": "நல்வரவு",
        "onb_begin": "என் பயணத்தைத் தொடங்கு",
        "onb_step_lang": "உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்",
        "onb_loc_title": "தொழுகை நேரங்களை அமைக்கவும்",
        "onb_loc_subtitle": "துல்லியமான தொழுகை நேரங்கள் மற்றும் நினைவூட்டல்களுக்கு இருப்பிடத்தை இயக்கவும்",
        "onb_loc_detecting": "நகரம் கண்டறியப்படுகிறது…",
        "onb_loc_success": "இருப்பிடம் கண்டறியப்பட்டது",
        "onb_loc_manual": "கைமுறையாக அமைக்கவும்",
        "onb_loc_enable": "இருப்பிடத்தை இயக்கு (GPS)",
        "onb_summary_title": "உங்கள் தினசரி திட்டம்",
        "onb_summary_goal": "உங்கள் குறிக்கோள்",
        "onb_summary_time": "விருப்பமான நேரம்",
        "onb_summary_location": "இருப்பிடம்"
    },
    "th": {
        "onb_goal_title": "เป้าหมายหลักของคุณคืออะไร?",
        "onb_goal_protection": "การปกป้องยามเช้าและเย็น",
        "onb_goal_habit": "สร้างนิสัยการรำลึกประจำวัน",
        "onb_goal_peace": "ค้นพบความสงบในยามยากลำบาก",
        "onb_goal_sunnah": "ปฏิบัติดุอาอ์ตามซุนนะฮฺอย่างครบถ้วน",
        "onb_time_title": "เวลาที่ดีที่สุดสำหรับคุณในการรำลึกคือเมื่อใด?",
        "onb_time_fajr": "หลังศุบฮิ",
        "onb_time_asr": "หลังอัศริ",
        "onb_time_sleep": "ก่อนนอน",
        "onb_time_anytime": "เวลาใดก็ได้",
        "onb_welcome": "ยินดีต้อนรับ",
        "onb_begin": "เริ่มต้นการเดินทางของฉัน",
        "onb_step_lang": "เลือกภาษาของคุณ",
        "onb_loc_title": "ตั้งค่าเวลาละหมาด",
        "onb_loc_subtitle": "เปิดใช้งานตำแหน่งเพื่อเวลาละหมาดที่แม่นยำและการเตือนอัซการอัตโนมัติ",
        "onb_loc_detecting": "กำลังค้นหาเมืองของคุณ…",
        "onb_loc_success": "ตรวจพบตำแหน่งแล้ว",
        "onb_loc_manual": "ตั้งค่าตำแหน่งด้วยตนเอง",
        "onb_loc_enable": "เปิดใช้งานตำแหน่ง (GPS)",
        "onb_summary_title": "แผนประจำวันของคุณ",
        "onb_summary_goal": "เป้าหมายของคุณ",
        "onb_summary_time": "เวลาที่สะดวก",
        "onb_summary_location": "ตำแหน่ง"
    }
}

i18n_dir = "assets/i18n"
for code, keys in translations.items():
    path = os.path.join(i18n_dir, f"{code}.json")
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        for k, v in keys.items():
            data[k] = v
        with open(path, "w", encoding="utf-8") as f:
            json.dump(data, f, ensure_ascii=False, indent=2)
            f.write("\n")
        print(f"Updated {code}.json with {len(keys)} keys.")
